import 'package:non_cognitive/data/model/student.dart';
import 'package:non_cognitive/utils/user_type.dart';

final students = [
  Student(
      idNumber: "1997274242",
      name: "Erni Nurhaeni",
      email: "erni@gmail.com",
      password: "erni123",
      gender: "Perempuan",
      no_telp: "0825627891982",
      photo: "",
      address: "Jl. Jalan",
      type: UserType.SISWA,
      id_sekolah: 1,
      studyStyle: "Kinestetik",
    id_tahun_ajaran: 1,
    tahun_ajaran: '2022/2023',
    token: '',
  ),
  Student(
      idNumber: "1986204282",
      name: "Ahmad Rusydi",
      email: "ahmadrusydi@gmail.com",
      password: "ahmadi128",
      gender: "Laki-laki",
      no_telp: "089962788982",
      photo: "",
      address: "Jl. Jalan",
      type: UserType.SISWA,
      id_sekolah: 1,
      studyStyle: "Visual",
    id_tahun_ajaran: 1,
    tahun_ajaran: '2022/2023',
    token: '',
  ),
  Student(
      idNumber: "19973790013",
      name: "Sutarna",
      email: "sutarna@gmail.com",
      password: "sutarna123",
      gender: "Laki-laki",
      no_telp: "088329370012",
      photo: "",
      address: "Jl. Jalan",
      type: UserType.SISWA,
      id_sekolah: 1,
      studyStyle: "Visual",
    id_tahun_ajaran: 1,
    tahun_ajaran: '2022/2023',
    token: '',
  ),
  Student(
      idNumber: "199668292700",
      name: "Nisa Putri",
      email: "nisap@gmail.com",
      password: "niputri123",
      gender: "Perempuan",
      no_telp: "087729269919",
      photo: "",
      address: "Jl. Jalan",
      type: UserType.SISWA,
      id_sekolah: 1,
      studyStyle: "Auditori",
    id_tahun_ajaran: 1,
    tahun_ajaran: '2022/2023',
    token: '',
  ),
  Student(
      idNumber: "198819720026",
      name: "Dede Supriatna",
      email: "dedesupriatna@gmail.com",
      password: "dede828",
      gender: "Laki-laki",
      no_telp: "085729720019",
      photo: "",
      address: "Jl. Jalan",
      type: UserType.SISWA,
      id_sekolah: 1,
    studyStyle: "Auditori",
    id_tahun_ajaran: 1,
    tahun_ajaran: '2022/2023',
    token: '',
  ),
  Student(
      idNumber: "1990262799128",
      name: "Ningsih Nurmalasari",
      email: "nurningsih@gmail.com",
      password: "ningsih123",
      gender: "Perempuan",
      no_telp: "082562781193",
      photo: "",
      address: "Jl. Jalan",
      type: UserType.SISWA,
      id_sekolah: 1,
      studyStyle: "Kinestetik",
    id_tahun_ajaran: 1,
    tahun_ajaran: '2022/2023',
    token: '',
  ),
];